import { chromium } from "playwright";
const URL = "https://pi-vps-mumbai.tail641fa8.ts.net/alpha/";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [], failed = [];
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
p.on("pageerror", (e) => errs.push("PAGEERROR: " + e.message));
p.on("requestfailed", (r) => failed.push(r.url() + " :: " + (r.failure()?.errorText || "")));
await p.goto(URL, { waitUntil: "load", timeout: 45000 });
await p.waitForTimeout(3500);
const h = await p.evaluate(() => document.body.scrollHeight);
const sections = await p.evaluate(() => document.querySelectorAll("section").length);
await p.screenshot({ path: "/tmp/aoh-live-top.png" });
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight / 2));
await p.waitForTimeout(1500);
await p.screenshot({ path: "/tmp/aoh-live-mid.png" });
await p.screenshot({ path: "/tmp/aoh-live-full.png", fullPage: true });
console.log("scrollHeight:", h, "sections:", sections);
console.log("CONSOLE ERRORS:", errs.length ? JSON.stringify(errs, null, 2) : "none");
console.log("FAILED REQUESTS:", failed.length ? JSON.stringify(failed, null, 2) : "none");
await b.close();
